language: python
python:

  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=config.settings.local
before_install:
  - pip install coveralls
install:
  - pip install -r requirements/test.txt
script:
  - flake8 permabots
  - coverage run manage.py test
after_success:
  - coveralls

